#####################################################################
# 默认配置文件
#####################################################################

common:
  title: 渠成集成运⾏环境
  lang: zh-cn
  theme: blue

service:
  - quickon:
    path: quickon\
    title: QuickOn
    enabled: true
    version: 1.0
    serviceCommand: sc create %QUICKON_SER_NAME% binPath= "%QUICKON_EXE%" start= demand displayname=%QUICKON_SER_NAME%
    exePath: quickonservice.exe
  