#####################################################################
# 项目配置文件
#####################################################################

common:
  title: window.title
  version: 3.0
  envPath:
    - "%ROOT_PATH%bin/git/cmd"
    - "%ROOT_PATH%bin/sliksvn"
    - "%ROOT_PATH%zbox/nssm/win32"

service:
  - quickon:
    enabled: true
    ignore: false
    serviceName: quickonzt
